NX627J: Remove duplicate tcmiface.jar
By compiling it from the source, I removed all pre-built items, files, and control statements.

I think the following error should be a conflict between the pre-built tcmiface and the source:
error: vendor/qcom/opensource/commonsys/dpm/Android.bp:3:1: module "tcmiface" variant "android_common": depends on non-java module "prebuilt_tcmiface"